config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "homepage#home"
  get "about", to:"aboutpage#about"
  resources :articals
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artical.rb
class Artical < ApplicationRecord
    validates :title, presence: true, length: {minimum: 5,maximum: 50}
    validates :description, presence: true, length: {minimum: 5,maximum: 50}
end 

app/controllers/aboutpage_controller.rb
class AboutpageController < ApplicationController
    def about
        
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def about
    end
end

app/controllers/articals_controller.rb
class ArticalsController < ApplicationController
    before_action :setArtical, only: [:show,:edit,:update,:destroy] 
    
    def show
        #byebug
    end

    def index
        @artical=Artical.all
    end

    def new 
        p "1"
        #p @artical.errors.full_messages
        @artical=Artical.new
    end

    def edit
    end

    def create
        @artical = Artical.new(artical_params)
        if @artical.save
            flash[:notice]="Artical is saved successfully"
            redirect_to @artical
          else
            respond_to do |format|
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @article.errors, status: :unprocessable_entity }
              end
          end
    end

    def update
        
        if Artical.update(artical_params)
            flash[:notice]="Artical has updated"
            redirect_to @artical
        else
            respond_to do |format|
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @article.errors, status: :unprocessable_entity }
              end
        end
    end

    def destroy
        
        @artical.delete
        redirect_to articals_path
    end
    private
    def setArtical()
        @artical= Artical.find(params[:id])
    end
    def artical_params
        params.require(:artical).permit(:title, :description)
    end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
    def home
    end
end

app/helpers/aboutpage_helper.rb
module AboutpageHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/aboutpage/about.html.erb
<h1>About Me</h1>
<h3>IT experience 7 years in analysis, design, development, and implementation phases of numerous client/server applications. Software Engineering experience in Design, Development & Support of Ruby on Rails applications in Airlines, Manufacturing, Finance, social networking, Healthcare, e-commerce, and other domains.</h3>

app/views/articals/_form.html.erb
<%Rails.logger.info("User created: #{@artical.errors.full_messages},, #{@artical.errors.full_messages.any?}")%>
<% if @artical.errors.full_messages.any? %>
  <h2>The following errors prevented the article from being saved</h2>
  <ul>
    <% @artical.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= link_to "Home", articals_path()%>
<%= form_with(model: @artical) do |f|%>

<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
</p>
<p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
</p>
<p>
    <%= f.submit %>
</p>

<% end %>

app/views/articals/edit.html.erb
<h1>Edit the Articals</h1>
<%= render "articals/form"%>

app/views/articals/index.html.erb
<h1>Articals Listing page</h1>

<table class="table table-dark">
    <thead>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
        <tbody>
        <% for i in @artical %>
            <tr>
            <td scope="col"><%= i.title %></td>
            <td scope="col"><%= i.description %></td>
            <td scope="col"><%= link_to "Show", artical_path(i.id)%></td>
            <td scope="col"><%= link_to "Edit", edit_artical_path(i.id)%></td>
            <td scope="col"><%= link_to "Delete", artical_path(i.id), data: { "turbo-method": :delete } %></td>
            </tr>
        </tbody>
        <% end %>
    
</table>
 <%= link_to "New", new_artical_path(@artical)%>

app/views/articals/new.html.erb
<h1>Create New Articals</h1>
<%= render "form"%>

app/views/articals/show.html.erb
<h1>This is articals page</h1>

<p><strong>Title: </strong><%= @artical.title %></p>
<p><strong>Description: </strong><%= @artical.description %></p>
<%= link_to "Home", articals_path()%>

app/views/homepage/home.html.erb
<h1>Welcome to HomePage</h1>

app/views/layouts/_messages.html.erb
    <% flash.each do |name,title|%>
    <p><%=title%></p>
    <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/messages"%>
    <%= yield %>
  </body>
</html>